#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_H_INVERT
#define PLOOPY_DRAGSCROLL_MULTIPLIER 0.25
// #define PLOOPY_DRAGSCROLL_FIXED
// #define PLOOPY_DRAGSCROLL_DPI 100
#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE 33

//#define SCROLLER_AR_SIZE 31
//#define SCROLLER_AR_SIZE 100

//#define SCROLL_THRESH_RANGE_LIM 100