#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_H_INVERT
// #define PLOOPY_DRAGSCROLL_MULTIPLIER 0.05
#define PLOOPY_DRAGSCROLL_FIXED
#define PLOOPY_DRAGSCROLL_DPI 150
#undef ROTATIONAL_TRANSFORM_ANGLE
#define ROTATIONAL_TRANSFORM_ANGLE 33

#define PLOOPY_DPI_OPTIONS { 600, 900, 1200 }
#define PLOOPY_DPI_DEFAULT 3
//#define PLOOPY_DPI_DEFAULT 900
//#define SCROLLER_AR_SIZE 31
//#define SCROLLER_AR_SIZE 100

//#define SCROLL_THRESH_RANGE_LIM 100